[font]
size = 15

# font-jetbrains-mono-nerd-font
normal.family = "JetBrainsMono Nerd Font"
normal.style = "SemiBold"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "BoldItalic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[window]
dimensions.columns = 160
dimensions.lines = 45
position.x = 75
position.y = 90
decorations = "buttonless"
opacity = 0.9
blur = true
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5
